# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 737944ab128c043edab867b1b6f48a08b72dea797c124bad72667f515d0fffcc8fa6c2e781df668fcad45f8992925fd6fe501b37f1ea781677d48da7693166b1

test:
  secret_key_base: 86e5a07daf9ec833ba17fa9193430085ac4cd1302ad55a4fdf89bdca369886fff962e6a5245d89f03a1fefdb182147b7f7e2244e58a3503c850688230f3c68a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
